typography_spectrum: 0.5083971938584
color:
  brandStrength: 0.4006495417561382
  lightness: 0.584698423044756
  saturation: 0.0038364147767424583
  rhythmicContrast: 0.21497563505545259
  brandColors:
    - '#292929'
    - '#5B7876'
    - '#8F9E8B'
    - '#F2E6B6'
    - '#412A22'
layout_spectrum: 0.3384676135610789
name: History
navigation:
  - name: Home
    url: 'http://thegrid.ai/mangoa/'
    type: external
  - name: Video
    url: 'http://thegrid.ai/mangoa_video/'
    type: external
  - name: Audio
    url: 'http://thegrid.ai/mangoa_audio/'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/Mangoa-197941767016658/?fref=ts'
    type: external
  - name: Soundcloud
    url: 'https://soundcloud.com/mangoa'
    type: external
title: MangoA
