typography_spectrum: 0.6163441229145974
color:
  brandStrength: 0.6066915856208652
  lightness: 0.7803958544973284
  saturation: 0.697906905785203
  rhythmicContrast: 0.4687857888638973
  brandColors:
    - '#B9121B'
    - '#4C1B1B'
    - '#F6E497'
    - '#FCFAE1'
    - '#BD8D46'
layout_spectrum: 0.44552347296848893
name: MangoA
navigation:
  - name: Home
    url: 'http://mangoa.world'
    type: external
  - name: Video
    url: 'https://www.youtube.com/user/mangoaoa/featured'
    type: external
  - name: Audio
    url: 'https://soundcloud.com/mangoa'
    type: external
  - name: Facebook
    url: 'https://www.facebook.com/Mangoa-197941767016658/?fref=ts'
    type: external
  - name: Upcoming Shows
    url: 'http://thegrid.ai/mangoa_shows/'
    type: external
title: ''
